### ISSUE TITLE
Scaffold project is missing in SDK binary distribution

### ISSUE THREAD

**Issue by tvadim** [telekom/voice-skill-sdk#47]
Trying to initialize a project with `vs init`:

```
Traceback (most recent call last):
  File "/home/vadim/PycharmProjects/test/.venv/bin/vs", line 8, in <module>
    sys.exit(main())
  File "/home/vadim/PycharmProjects/test/.venv/lib/python3.8/site-packages/skill_sdk/__main__.py", line 55, in main
    arguments.command(arguments)
  File "/home/vadim/PycharmProjects/test/.venv/lib/python3.8/site-packages/skill_sdk/cli/init.py", line 68, in execute
    copy_tree(scaffold_path.__str__(), path.__str__())
  File "/usr/lib/python3.8/distutils/dir_util.py", line 126, in copy_tree
    raise DistutilsFileError(
distutils.errors.DistutilsFileError: cannot copy tree '/home/vadim/PycharmProjects/test/.venv/lib/python3.8/site-packages/skill_sdk/cli/scaffold': not a directory
```

**Comment by tvadim** [comment]
Closed in https://github.com/telekom/voice-skill-sdk/releases/tag/1.0.1
