### ISSUE TITLE
Issue after using vs init

### ISSUE THREAD

**Issue by buffy93** [telekom/voice-skill-sdk#62]
I tried to use the command  `vs init` after installing the voice skill sdk. But i get the following issue:
`Traceback (most recent call last):
  File "/home/buffy/.pyenv/versions/3.9.6/bin/vs", line 8, in <module>
    sys.exit(main())
  File "/home/buffy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/skill_sdk/__main__.py", line 62, in main
    arguments.command(arguments)
  File "/home/buffy/.pyenv/versions/3.9.6/lib/python3.9/site-packages/skill_sdk/cli/init.py", line 26, in execute
    import questionary
ModuleNotFoundError: No module named 'questionary'
`

**Comment by tvadim** [comment]
@buffy93 It may happen if you did not install the `dev` extra, like:

```bash
pip install skill-sdk[dev]
```

**Comment by 4thel00z** [comment]
Note that in zsh you need to escape the brackets:

```
pip install 'skill-sdk[dev]'
```
